### ISSUE TITLE
Mobile keyboard coming up

### ISSUE THREAD

**Issue by gedw99** [enrian/vue-pikaday#1]
On mobile when selecting the show button the cal is displayed, but the keyboard is also opened which you don't want.

Tested on Android chrome stable 

Am not sure how to solve this in Vuejs.
Not even sure if it's possible to prevent this

**Comment by NetCZ** [comment]
Hi @gedw99, thanks for raising this up. 

This particular problem have nothing to do with Vue or Pikaday themselves, its how browser handles input events. 

But I've successfully tested simple solution - setting `readonly` attribute to `vue-pikaday` tag. If you wish to do this only for mobile devices, I'd recommend to use "Modernizr" and check for touch events feature.

Ping me if it helped.
