### ISSUE TITLE
bad things happen when you clear input 

### ISSUE THREAD

**Issue by piotr-lottestyle** [enrian/vue-pikaday#14]
1. v-model value becomes a string `[object InputEvent]`
2. Deprecation warning is issued by moment
3. Invalid prop error is issued by vue

**Comment by NetCZ** [comment]
Hi @piotr-lottestyle, thanks for reporting the issue. It's fixed in https://github.com/enrian/vue-pikaday/releases/tag/v1.0.3, please update the package.
