### ISSUE TITLE
Great job!!! Have a few questions

### ISSUE THREAD

**Issue by chrismartinez99** [enrian/vue-pikaday#15]
First - great job!! This works great and (almost exactly) what I was looking for!

My questions/issues:
- How do we set the onSelect callback function?
- is there a way to set the date value so it's not a full Moment string (i.e., "[native Date Thu Sep 20 2018 00:00:00 GMT-0500 (Chicago Daylight Time)]", if I only want something like 2018-09-20? Setting the format only sets the display.

Again, thanks!

**Comment by NetCZ** [comment]
Hi @chrismartinez99,
glad to hear this package helped you.

To your questions:
- onSelect can be set through `options` prop, see [docs](https://enrian.github.io/vue-pikaday/guide/usage.html#passing-options-to-underlying-pikaday)
- if I understand correctly, you want to consume Date object produced by component and display it somewhere else, correct? In that case I'd recommend rather to use [Vue.filters](https://vuejs.org/v2/guide/filters.html) instead

**Comment by chrismartinez99** [comment]
Great, thanks for getting back to me. I'll try both options.
