### ISSUE TITLE
v-model 2-way binding?

### ISSUE THREAD

**Issue by z3malford** [enrian/vue-pikaday#3]
It seems that changes in the `v-model` value don't update the picker `<input>`. After initialization it seems to be only one way only.

Changing the `v-model` value from the containing component should cause the `<input>` to get updated accordingly IMHO. 

Thanks!

BTW: my use model for this is I want to have some preset buttons like "Today", "Previous Day" (subtracts one day from the currently selected value), etc.

**Comment by NetCZ** [comment]
Thanks @z3malford, will check it and report back

**Comment by NetCZ** [comment]
@z3malford fixed in https://github.com/enrian/vue-pikaday/releases/tag/v1.0.2, please upgrade, thanks again for pointing this out
