### ISSUE TITLE
Is it possible to call pikaday methods such as 'setMinDate'?

### ISSUE THREAD

**Issue by davidwaterston** [enrian/vue-pikaday#79]
Is it possible to call some of the pikaday methods such as 'setMinDate'?
I'm trying to create a date range picker (from date --> to date). Setting the minDate and maxDate properties in options works well initially but they don't seem to be reactive i.e. making a change to he maxDate after initialisation seems to pass it on to pikaday but doesn't make any change to the component.

I'd like to be able to change the minDate for the 'to date' and the maxDate for the 'from date' depending on what dates the user selects. 'setMinDate' looks like it would allow it. Is there a way to call those functions, or another way to do it?

**Comment by NetCZ** [comment]
Hi @davidwaterston,
calling methods of "Pikaday" directly can be done through `ref`, something like:

**template**
```html
<vue-pikaday ref="pika" />
```

**component**
```js
this.$refs.pika.pikaday.setMinDate(...);
```

See https://codepen.io/NetCZ/pen/pXzewg with example.

**Comment by davidwaterston** [comment]
Thanks @NetCZ 
That worked perfectly... and is kind of obvious now that I see it.
