### ISSUE TITLE
Snyk as dependency necessary? DevDepency enough?

### ISSUE THREAD

**Issue by doits** [enrian/vue-pikaday#91]
I just got an update and wondered about all the new dependencies. Looks like [snyk](https://github.com/enrian/vue-pikaday/blob/master/package.json#L47) was added as a regular dependency.

I wonder if this is really necessary as a regular dependency. Isn't it enough to have it as a dev dependency, so it is not bundled when published?

**Comment by NetCZ** [comment]
Hi @doits, thanks for noticing. Of course, you're right, it's being fixed by #92.
